### ISSUE TITLE
No existeix la cadena coursequotas:manage

### ISSUE THREAD

**Issue by reskit** [projectestac/moodle-report_coursequotas#4]
Falta afegir la cadena coursequotas:manage al lang, ara mateix cada vegada que s'accedeix a la pantalla de rols apareix el següent missatge:

> PHP Notice:  Invalid get_string() identifier: 'coursequotas:manage' or component 'report_coursequotas'. Perhaps you are missing $string['coursequotas:manage'] = '';

**Comment by sarjona** [comment]
Gràcies @reskit !!

Afegides les cadenes que faltaven al commit https://github.com/projectestac/moodle-report_coursequotas/commit/07440934f89a9f0b35167f9c67007e80b8c1a5e7
